server:
  port: 8081
  servlet:
    context-path: /cubd
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:coin # h2 database 連接位址
    driver-class-name: org.h2.Driver # 配置driver
    username: sa # database 用戶名
    password: sa # database 密碼

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
configs:
  apis:
    coinAPI: https://api.coindesk.com/v1/bpi/currentprice.json